### ISSUE TITLE
How do I know if the Dialog showing?

### ISSUE THREAD

**Issue by Ctrl-Space** [Kaopiz/KProgressHUD#10]
aha.. will you add progress.isShowing() in next version ?

**Comment by tuanna-hsp** [comment]
Thank for your feedback :+1: 
That definitely a big mistake, i will add it soon :)

**Comment by fukemy** [comment]
hi, 4 years since you said adding new funtion?

**Comment by tuanna-hsp** [comment]
Yeah I have already did it in 1bd8dc8

**Comment by fukemy** [comment]
sorry i just see your lib is no longer maintained for long times, then have a silly question above. I just want to ask you about show hud based on application. That mean i have some function in application that need to show hud, can you provide me some way to did it? Thanks

**Comment by tuanna-hsp** [comment]
@fukemy There is guide on how to install the library and some examples in the README.
You could take a look.
https://github.com/Kaopiz/KProgressHUD/blob/master/README.md

**Comment by fukemy** [comment]
i used your library for 2 projects 👍  ( about 1 years since first time i see your lib).  But now my project require some problems, all i need is show hud in application class, not activity.
 I now your lib is display hud based on activityContext, not applicationContext. It's hard to me, because get top activity from Application class function is almost deprecated

**Comment by tuanna-hsp** [comment]
@fukemy Unfortunately our implementation uses a customized Dialog to display the hub. 
Since Dialog can only be created from Activity context, it is not possible to use Application context.

**Comment by fukemy** [comment]
ok tks, solved by registerLifecircleCallback in application then save current activity for work with dialog
